### ISSUE TITLE
Moving Sandbox Annual Reviews to TAGs with Liaison support

### ISSUE THREAD

**Issue by TheFoxAtWork** [cncf/toc#1123]
On Tuesday July 18th, the TOC held a public discussion on how to conduct Sandbox Annual reviews moving forward and transitioning them to TAGs.

Out of the discussion we added the following areas that need covered in this process:

- Account for archive - notify TOC liaisons and this should be a high bar for sandbox
- Identifying projects in Sandbox for an unusually long time - indicators of this, progress, next steps
- Ensuring we capture where and if projects need support to continue to move forward and directing those requests appropriately
- Distributing Annual Reviews among all the TAGs, projects have TAGs loosely aligned or may fall under multiple TAGs, whereas some TAGs do not have any projects to review
- Looking for community growth indicators such as additional maintainers and contributors
- Create TAG review badges for TAG members that contribute and conduct Annual reviews to ensure recognition of this important work
- Assist in building out TAG community and incentivizing projects to pay it forward through returning contributions to the TAG
- identifying areas for projects to integrate and collaborate with others to achieve efficiencies within the ecosystem for adopters
- finalization of voting

@TheFoxAtWork  took the action to write up a lightweight process over the next two weeks with contributions from several individuals on the call (reminder please DM me if interested). Our goal is to have these 35 completed by **end of September** and to have the TOC liaisons partner with their TAGs in completing these reviews initially to ease the transition.

```[tasklist]
### Tasks
- [x] Draft the lightweight process to share on the TOC channel and mailing list:  Due August 1st (edit:[ link to draft](https://docs.google.com/document/d/1cE9zutKh3ZGzEzZr5CZ_ck66JJ1J5mLeNYELVLbxf-Q/edit))
- [x] Assign Annual Reviews to TAGs to ensure appropriate distribution of work: ~Aug 4th
- [x] TOC Liaisons and TAGs begin exercising the lightweight process in conducting reviews, providing feedback on this issue as they experience shortcomings, challenges, and observations. ~ Aug 5th
- [ ] Annual Reviews are completed with recommendations from TAGs (to projects and to the TOC) ~ Sept 18th
- [ ] TOC public meeting to review the outcome, identify areas of finalization, (general retrospective)
- [ ] TOC meet to confirm annual reviews. ~ Sept 26th
- [ ] Recommendations for improvements on the proposed process are integrated and a PR is filed.
```

**Comment by TheFoxAtWork** [comment]
From today’s slides, here are the focus areas i covered (built from the guide posts but less specific, more indicators of what we are to look at):
## Sandbox
Sandbox projects are considered early stage and experimental. We expect projects to still be growing and learning in a variety of areas.  When conducting annual reviews of Sandbox projects, we look for the following indicators of a healthy yet maturing project:

- **Community growth and development are ongoing**.  The project may hold meetings, discussions, or other forms of community-focused communication. The frequency of these are set by the project. It is expected the project is balancing community growth with project development.
- **Appropriate project governance.** The project has an initial, clearly defined governance that addresses the core areas needed to successfully operate the project. The project will likely have a minimal history of changes to the governance beyond initial introduction as they may be too early to fully exercise their governance process (such as maintainer emeritus changes). This governance should capture the basics of decision making, particularly as it pertains to PR reviews and how contributors may participate in the project.
- **Long-term planning exists.** The project defines long term goals, objectives, features or releases. It is not expected the project will achieve every define goal or objective within the timeframe or release they specify, rather that they are considering the future of the project and tracking completion of those activities. This may be extremely lightweight in the form of identifying primary components in a v1.0 release or it may be more detailed and use project boards, milestones, and other planning flows.
- **Development is ongoing and progressive towards versioned releases.** Early projects are likely to have significant variability in the frequency by which development happens. They may experience bursts of contributions and commits, slow steady pacing, or a combination thereof. Each project is different, however we should see some form of progress which may be features and bug fixes, stability improvements, project packaging infrastructure, and tests. Projects should not appear to be in maintenance or sustainment mode - this is an indicator of a project health concern.
- **Adoption is picking up**. While the project is early, we may see one or two more adopters, users, or entities exploring the viability of the project for their needs. We’re not likely to see significant changes within their adoption file, however indicators of features requests and indicators of positive attention by potential adopters.
- **Self-awareness**. The project has reasonable awareness of their overall maturity and progress to incubation. They understand their path to incubation and any activities still outstanding in order to be ready to apply.

**Comment by TheFoxAtWork** [comment]
Individuals who expressed interest on the Call to assist in drafting that lightweight process:
@nikhita , @leonardpahlke , @joshgav , @raravena80 , @angellk 
Please confirm, if i missed anyone, please comment so i can make sure you are added here.

**Comment by krishnakv** [comment]
Hi @TheFoxAtWork , do add me also and looking forward to working with the group.

**Comment by xmulligan** [comment]
I'm interested in helping out with the TAG Network reviews

**Comment by Saim-Safdar** [comment]
Hi @TheFoxAtWork please do include me as well, happy to take part in this activity,

**Comment by TheFoxAtWork** [comment]
hi @Saim-Safdar ! I've added you to the thread in the toc channel where the discussion is happening.

**Comment by TheFoxAtWork** [comment]
So we’re at Wednesday, I’d like us to being narrowing down on the must haves for Friday, and identifying areas of future improvements so we can convert them to issues and track them.  I’m going to go through comments and content today and identify anything that is great for later and move it to a future improvements section. .  My hope is come Monday we’ll be in a good spot with clear instructions/expectations and can begin assigning TAGs.

**Comment by TheFoxAtWork** [comment]
https://lists.cncf.io/g/cncf-toc/message/8212

> All, 
> 
> Thank you again for your patience as work through how to approach Sandbox Annual Reviews. I'd like to thank the wonderful volunteers and reviewers who have spent time pulling this together as a first step to shift Sandbox Annual Reviews to TAGs. We anticipate that this initial step will be revisited, iterated upon, and formalized in the TOC Repo when the current bulk of Annual Reviews are complete.  Below you will find next steps and a link to the document.
> 
> Next Steps:
> 1. Distribution of Annual Reviews among the TAGs - [please review this section on distribution and begin assigning](https://docs.google.com/document/d/1cE9zutKh3ZGzEzZr5CZ_ck66JJ1J5mLeNYELVLbxf-Q/edit#heading=h.3q880k74iszd)
> 2. Select an annual reviewer - [information on selecting an annual reviewer is here](https://docs.google.com/document/d/1cE9zutKh3ZGzEzZr5CZ_ck66JJ1J5mLeNYELVLbxf-Q/edit#heading=h.3kswwrntmsg)
> 3. Conduct the annual review evaluation - [comprehensive instructions and considerations are here, please note this includes the recommendation and TOC actions](https://docs.google.com/document/d/1cE9zutKh3ZGzEzZr5CZ_ck66JJ1J5mLeNYELVLbxf-Q/edit#heading=h.tru60t8oad7m)
> 4. Provide feedback on [Issue 1123](https://github.com/cncf/toc/issues/1123) as you work through this
> 5. Annual Reviews are completed by Sept 18th for discussion/retrospective on the process on Sept 19th TOC meeting.
> 6. Process is formalized in a PR on the TOC repo.
> 
> The entirety of the process, including the links above and additional information, is documented here: https://docs.google.com/document/d/1cE9zutKh3ZGzEzZr5CZ_ck66JJ1J5mLeNYELVLbxf-Q/edit?usp=sharing
> 
> The document still includes open comments and additional discussion background for community transparency and consideration. If you have any questions, please ask them on [Issue 1123](https://github.com/cncf/toc/issues/1123) or in [this slack thread in the #tag-chairs channel](https://cloud-native.slack.com/archives/CSCPTLTPE/p1690925340512839).
> 
> Please remember to keep an open mind as we try this out, we will continue to iterate and improve our processes as we try new things and learn what does and doesn't work. Thank you again and to our projects, a huge thank you for your patience.

**Comment by craigbox** [comment]
> I'm interested in helping out with the TAG Network reviews

as am I.

**Comment by angellk** [comment]
@TheFoxAtWork beginning to review a project - first item to note is adding this line to the beginning of [Sandbox Annual Review](https://github.com/cncf/toc/blob/main/process/sandbox-annual-review.md) process doc:

> Include a link to last year's Annual Review or, if none, Sandbox Application approval

**Comment by TheFoxAtWork** [comment]
Sandbox annual reviews no longer required in favor of future automation (Project Health and Annual Review Board). CC @jeefy
