### ISSUE TITLE
[ARCHIVE] SMI

### ISSUE THREAD

**Issue by amye** [cncf/toc#1180]
- [x] TOC vote to archive passed
- [x] Move logo to archived on CNCF.io	
- [x] Remove from landscape		
- [x] Archive maintainers mailing list	
- [x] Remove ML from maintainers@ mailing group
- [x] Remove/Archive on maintainers.cncf.io
- [x] Remove logo from all slide decks	
- [x] Remove logo from event sites	
- [x] Move logo to archived in artwork	
- [x] Archive DevStats
- [x] Notify Speakers team to remove from CFPs	
- [x] Remove from service desk or archive	
- [x] Remove from CNCF store
- [x] Remove from [CLOMonitor data](https://raw.githubusercontent.com/cncf/clomonitor/main/data/cncf.yaml)
- [x] Remove from FOSSA 

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by amye** [comment]
@lukaszgryglicki - FYI

**Comment by caniszczyk** [comment]
https://github.com/cncf/landscape/pull/3533

**Comment by RobertKielty** [comment]
@amye There's an Team for SMI registered in FOSSA should it be removed?

**Comment by amye** [comment]
> @amye There's an Team for SMI registered in FOSSA should it be removed?

Yes!

**Comment by amye** [comment]
@lukaszgryglicki - your help to archive in Devstats! Thank you!

**Comment by lukaszgryglicki** [comment]
Do I need to do anything else?

**Comment by bridgetkromhout** [comment]
I've closed out all PRs/issues on GitHub, archived all repositories, and added an archival notice at the "servicemeshinterface" organization level.

**Comment by bridgetkromhout** [comment]
Can someone with permissions on CNCF Slack archive the #smi channel? See: https://cloud-native.slack.com/archives/C0105GB1BJQ/p1697821086606319

**Comment by amye** [comment]
> Can someone with permissions on CNCF Slack archive the #smi channel? See: https://cloud-native.slack.com/archives/C0105GB1BJQ/p1697821086606319

done!
