### ISSUE TITLE
[Incubation] WasmEdge Incubation Application

### ISSUE THREAD

**Issue by alabulei1** [cncf/toc#1316]
#  WasmEdge Runtime Incubation Application

Project Repo(s): https://github.com/WasmEdge/WasmEdge
Project Site: https://wasmedge.org/
Sub-Projects: None
Communication: #WasmEdge in the CNCF slack channel and the seperate WasmEdge Discord server.

Project points of contacts: 
Michael Yuan, michael@secondstate.io

### Adoption Assertion

_The project has been adopted by the following organizations in a testing and integration or production capacity:_

   A list of WasmEdge adopters can be found at [here](https://wasmedge.org/docs/contribute/users). Additionally, many of them are not disclosed.

### Suggested

N/A

### Required

- [X] **Give a presentation and engage with the domain specific TAG(s) to increase awareness**

    The WasmEdge runtime was presented to the wg-wasm group under the TAG-runtime in July 2023. You can view the recorded video [here](https://youtu.be/1VsoJ2hBLBk ).

- [ ] **TAG provides insight/recommendation of the project in the context of the landscape**

To be completed by TAG runtime.

- [X] **All project metadata and resources are [vendor-neutral](https://contribute.cncf.io/maintainers/community/vendor-neutrality/).**

    When WasmEdge joined the CNCF Sandbox in 2021, the project was renamed to ensure vendor neutrality.

    * Communication: WasmEdge maintains its own communication channels such as its website, social media accounts, Slack, and Discord server.
    * Hosting: WasmEdge hosts community meetings, events, resources, and infrastructure on vendor-neutral, third-party platforms.
    * Architectural Decisions: WasmEdge is a cross-platform runtime built on open-source and vendor-neutral tools, such as LLVM and Rust. It supports many different application frameworks, OSes, CPUs and GPUs. 
    * Governance: WasmEdge is self-governing, adhering to the CNCF code of conduct. The [GOVERNANCE](https://github.com/WasmEdge/WasmEdge/blob/master/docs/GOVERNANCE.md) document clearly defines the contribution-based process and leadership structure.

- [X] **Review and acknowledgement of expectations for [Sandbox](https://sandbox.cncf.io) projects and requirements for moving forward through the CNCF Maturity levels.**		

    [Met during sandbox onboarding](https://github.com/cncf/toc/issues/646).

 

- [ ] **Due Diligence Review.**

Completion of this due diligence document, resolution of concerns raised, and presented for public comment satisifies the Due Diligence Review criteria.

To be completed by TOC sponsor.

- [X] **Additional documentation as appropriate for project type, e.g.: installation documentation, end user documentation, reference implementation and/or code samples.**

    * End user and developer documentation is available at here: https://wasmedge.org/docs/
    * Contribution guide is available at here: https://wasmedge.org/docs/contribute/overview

## Governance and Maintainers

Note: this section may be augmented by the completion of a Governance Review from TAG Contributor Strategy.

### Suggested

- [X] **Clear and discoverable project governance documentation.**

    The Governance documentation can be found under the WasmEdge GitHub repo: https://github.com/WasmEdge/WasmEdge/blob/master/docs/GOVERNANCE.md

- [X] **Governance has continuously been iterated upon by the project as a result of their experience applying it, with the governance history demonstrating evolution of maturity alongside the project's maturity evolution.**

Example: The WasmEdge community has evolved its code of conduct to require clear acknowledgement of derivative work. Those lessons were learnt from disputes between two LFX interns in our community.

 

- [X] **Governance is up to date with actual project activities, including any meetings, elections, leadership, or approval processes.**

 

- [X] **Governance clearly documents [vendor-neutrality](https://contribute.cncf.io/maintainers/community/vendor-neutrality/) of project direction.**

 

- [X] **Document how the project makes decisions on leadership, contribution acceptance, requests to the CNCF, and changes to governance or project goals.**

 

- [X] **Document how role, function-based members, or sub-teams are assigned, onboarded, and removed for specific teams (example: Security Response Committee).**

 

- [X] **Document a complete maintainer lifecycle process (including roles, onboarding, offboarding, and emeritus status).**

    The contributor lifecycle can be found here: https://github.com/WasmEdge/WasmEdge/blob/master/docs/GOVERNANCE.md

- [X] **Demonstrate usage of the maintainer lifecycle with outcomes, either through the addition or replacement of maintainers as project events have required.**

    The documentaton about adding and removing maintainers can be found here: https://github.com/WasmEdge/WasmEdge/blob/master/docs/GOVERNANCE.md

- [x] **If the project has subprojects: subproject leadership, contribution, maturity status documented, including add/remove process.**

N/A

 

### Required

- [X] **Document complete list of current maintainers, including names, contact information, domain of responsibility, and affiliation.**

    You can find the list of reviewers, committers, and maintainers [here](https://github.com/WasmEdge/WasmEdge/blob/master/docs/OWNER.md).

- [X] **A number of active maintainers which is appropriate to the size and scope of the project.**
    
    The WasmEdge runtime project has 4 maintainers, all of whom are active.

- [X] **Code and Doc ownership in Github and elsewhere matches documented governance roles.**

    DCO is enforced on all code contributions.
     https://github.com/WasmEdge/WasmEdge/blob/master/docs/OWNER.md reflects the maintainer lists.

- [X] **Document agreement that project will adopt CNCF Code of Conduct.**

  Adopted during sandbox onboarding. 

- [X] **CNCF Code of Conduct is cross-linked from other governance documents.**

  See the [CODE_OF_CONDUCT here](https://github.com/WasmEdge/WasmEdge/blob/master/docs/CODE_OF_CONDUCT.md).

- [x] **All subprojects, if any, are listed.**

N/A

 

## Contributors and Community

Note: this section may be augmented by the completion of a Governance Review from TAG Contributor Strategy.

### Suggested

- [X] **Contributor ladder with multiple roles for contributors.**

    Currently, WasmEdge has three roles of contributor: reviewer, commiter, and maintainer. See the [GOVERNANCE](https://github.com/WasmEdge/WasmEdge/blob/master/docs/GOVERNANCE.md) documentation.

### Required

- [X] **Clearly defined and discoverable process to submit issues or changes.**

    [Guides for creating a GitHub issue](https://wasmedge.org/docs/contribute/#reporting-issues).

- [X] **Project must have, and document, at least one public communications channel for users and/or contributors.**

    The public communicaion channel is published on [WasmEdge docs](https://wasmedge.org/docs/contribute/community) and [project README.md](https://github.com/WasmEdge/WasmEdge?tab=readme-ov-file#community).

- [X] **List and document all project communication channels, including subprojects (mail list/slack/etc.).  List any non-public communications channels and what their special purpose is.**

    The primary communication channel for WasmEdge is GitHub, where we welcome all kinds of issues, discussions, and pull requests.

    For real-time communication, you can join #WasmEdge on the CNCF Slack workspace or the [WasmEdge Discord server](https://discord.gg/s6B4Wd9QNh).

    Additionally, we maintain a dedicated Twitter account for updates and announcements related to WasmEdge.

    While we have a mailing list through lists.cncf.io, it is only for very infrequent announcements to avoid spam.

    You can find more information about these communication channels in the WasmEdge project [README.md](https://github.com/WasmEdge/WasmEdge?tab=readme-ov-file#community) and [WasmEdge docs](https://wasmedge.org/docs/contribute/community).

- [X] **Up-to-date public meeting schedulers and/or integration with CNCF calendar.**

    We have a community meeting page under the CNCF community: https://community.cncf.io/wasmedgeruntime-community/

- [X] **Documentation of how to contribute, with increasing detail as the project matures.**

    The contribution guide can be found [here](https://wasmedge.org/docs/contribute/).

- [X] **Demonstrate contributor activity and recruitment.**

    [76 commiters have created PRs in the last 12 months](https://wasmedge.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%20year&var-metric=merged_prs&var-repogroup_name=All&var-country_name=All&var-companies=All) and [278 contributors have interacted with  the project on GitHub](https://wasmedge.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=All&var-country_name=All&var-companies=All).

### Suggested

- [X] **Roadmap change process is documented.**

     Roadmap can be found [here](https://github.com/WasmEdge/WasmEdge/blob/master/docs/ROADMAP.md). The items are proposed by community members, approved by maintainers, and tracked in GitHub.

- [X] **History of regular, quality releases.**

    
The WasmEdge community has released sixteen new versions of the software since joining CNCF sandbox.

* [version 0.8.0](https://github.com/WasmEdge/WasmEdge/releases/tag/0.8.0)
* [version 0.8.1](https://github.com/WasmEdge/WasmEdge/releases/tag/0.8.1)
* [version 0.8.2](https://github.com/WasmEdge/WasmEdge/releases/tag/0.8.2)
* [version 0.9.0](https://github.com/WasmEdge/WasmEdge/releases/tag/0.9.0)
* [version 0.10.0](https://github.com/WasmEdge/WasmEdge/releases/tag/0.10.0)
* [version 0.11.0](https://github.com/WasmEdge/WasmEdge/releases/tag/0.11.0)
* [version 0.11.1](https://github.com/WasmEdge/WasmEdge/releases/tag/0.11.1)
* [version 0.11.2](https://github.com/WasmEdge/WasmEdge/releases/tag/0.11.2)
* [version 0.12.0](https://github.com/WasmEdge/WasmEdge/releases/tag/0.12.0)
* [version 0.12.1](https://github.com/WasmEdge/WasmEdge/releases/tag/0.12.1)
* [version 0.13.0](https://github.com/WasmEdge/WasmEdge/releases/tag/0.13.0)
* [version 0.13.1](https://github.com/WasmEdge/WasmEdge/releases/tag/0.13.1)
* [verison 0.13.2](https://github.com/WasmEdge/WasmEdge/releases/tag/0.13.2)
* [verison 0.13.3](https://github.com/WasmEdge/WasmEdge/releases/tag/0.13.3)
* [version 0.13.4](https://github.com/WasmEdge/WasmEdge/releases/tag/0.13.4)
* [version 0.13.5](https://github.com/WasmEdge/WasmEdge/releases/tag/0.13.5)

### Required 

- [X] **Document project goals and objectives that illustrate the project’s differentiation in the Cloud Native landscape as well as outlines how this project fulfills an outstanding need and/or solves a problem differently.**

     WasmEdge is a lightweight, high-performance, OCI-compatible, and extensible WebAssembly runtime for cloud-native, edge, and decentralized applications. It powers serverless apps, embedded functions, microservices, smart contracts, and IoT devices. Compared with other WebAssembly runtimes, WasmEdge is a fully featured and yet lightweight runtime with support for advanced networking, asynchronous functions, AI inference, and container tooling. WasmEdge could be seamlessly integrated with existing cloud-native ecosystems like Kubernetes and Docker. You can learn more about WasmEdge runtime [here](https://wasmedge.org/docs/start/wasmedge/features).

- [X] **Document what the project does, and why it does it - including viable cloud native use cases.**

    WasmEdge use cases includes serverless apps, AI inference, embedded functions, microservices, smart contracts, and IoT devices. They are documented [here](https://wasmedge.org/docs/category/wasmedge-use-cases). Specially, cloud-native use cases include [serverless functions and microservices](https://wasmedge.org/docs/category/serverless-platforms).

- [X] **Document and maintain a public roadmap or other forward looking planning document or tracking mechanism.**

    The WasmEdge project roadmap can be found [here](https://github.com/WasmEdge/WasmEdge/blob/master/docs/ROADMAP.md).    

- [X] **Document overview of project architecture and software design that demonstrates viable cloud native use cases, as part of the project's documentation.**

   * WasmEdge’s internal architecture: https://wasmedge.org/docs/contribute/internal
   * WasmEdge's integration with container tools: https://wasmedge.org/docs/develop/deploy/intro

- [X] **Document the project's release process.**

    The WasmEdge release process can be found here: https://wasmedge.org/docs/contribute/release

## Security

Note: this section may be augemented by a joint-assessment performed by TAG Security.

### Suggested

N/A

### Required

- [X] **Clearly defined and discoverable process to report security issues.**

    The securirty policy can be found here: https://github.com/WasmEdge/WasmEdge/blob/master/SECURITY.md
    
    
- [X] **Enforcing Access Control Rules to secure the code base against attacks (Example: two factor authentication enforcement, and/or use of ACL tools.)**

The WasmEdge code base is hosted on GitHub under the CNCF organization. It adheres to access control best practices of both GitHub and CNCF, including two-factor auth for repo admins, protected main branches, and required DCA signatures for every commit.

WasmEdge is adpoted by [Google OSS Fuzz](https://github.com/google/oss-fuzz/tree/master/projects/wasmedge). It strictly adheres to Google program requirements to fix identified bugs in a timely manner.

- [X] **Document assignment of security response roles and how reports are handled.**

The WasmEdge security reporting and response policies are described in the [SECURITY.md](https://github.com/WasmEdge/WasmEdge/blob/master/SECURITY.md) document.

- [X] **Document Security Self-Assessment.**

WasmEdge has a large number of CI tests that must pass for each release. Many of these tests are security related. It also makes extensive use of code coverage tools that generate reports for every PR.

WasmEdge is also an active participant in Google's OSS fuzz program. All issues identified by fuzzing are fixed before every release.

 

- [X] **Achieve the Open Source Security Foundation (OpenSSF) Best Practices passing badge.**

    [OpenSSF Best Practices passed](https://www.bestpractices.dev/en/projects/5059).

### Suggested

N/A

### Required

- [X] **Publicly documented list of adopters, which may indicate their adoption level (dev/trialing, prod, etc.)**

    [Adopters](https://wasmedge.org/docs/contribute/users)

- [X] **Used in appropriate capacity by at least 3 independent + indirect/direct adopters, (these are not required to be in the publicly documented list of adopters)**

    These will be provided to our TOC sponsor.

The project provided the TOC with a list of adopters for verification of use of the project at the level expected, i.e. production use for graduation, dev/test for incubation.

- [ ] **TOC verification of adopters.**

    To be completed by the TOC

Refer to the Adoption portion of this document.

- [X] **Clearly documented integrations and/or compatibility with other CNCF projects as well as non-CNCF projects.**

    With WasmEdge, users can use their already-familiar cloud-native and container tools to manage lightweight, portable, and secure Wasm apps. WasmEdge has integrated with crun, youki, containerd’s runwasi (A CNCF project), and Docker Desktop. WasmEdge has demonstrated integrations with Kubernetes (A CNCF project), SuperEdge (A CNCF project), OpenYurt (A CNCF project), Kuasar (A CNCF project)and KubeEdge (A CNCF project). WasmEdge aligns with the mission of CNCF in empowering organizations to bring the cloud-native and serverless application paradigms to “edge” scenarios. 

## Additional Information

N/A

**Comment by dims** [comment]
Hi @alabulei1 @hydai @q82419  @ibmibmibm

Here are some suggestions to improve the governance, security, and code of conduct aspects of the WasmEdge project based on our current assessment of the details you have provided and are available to everyone as part of the project:

### Governance:

* Consider adding a section for sub-projects if there are any
  * see https://contribute.cncf.io/maintainers/templates/governance-subprojects/
  * see https://github.com/containerd/project/blob/main/GOVERNANCE.md for examples of other projects that have documented this well
* Add information about emeritus maintainers if applicable.
* Document the Developer Certificate of Origin (DCO) process somewhere.
* If it's a single vendor project, consider having a "Council" for roadmap decisions, similar to the CNCF template here - https://contribute.cncf.io/maintainers/templates/
* Document how technical decisions are made, including whether the design process is public, whether non-maintainers can participate, and provide examples of decisions made in a neutral/community-based fashion.

### Security:

* The security process should be owned and run by community participants, not just a vendor (see email in SECURITY.md)
* Adopt suggestions from the CNCF security guidelines, especially regarding embargoes and notifications - https://contribute.cncf.io/maintainers/security/security-guidelines/
* Consider using the CNCF tag-security templates for security-related files - https://github.com/cncf/tag-security/tree/main/project-resources

### Code of Conduct:

* Separate the dependency/license/copyright information from the CODE_OF_CONDUCT.md file.
* Have a dedicated email address or contact point for reporting conduct issues, separate from the general mailing list ( WasmEdge@googlegroups.com )
* Ensure that the CODE_OF_CONDUCT.md files in different repositories are consistent and point to the correct location. ( https://github.com/WasmEdge/docs/blob/main/CODE_OF_CONDUCT.md should point to https://github.com/WasmEdge/WasmEdge/blob/master/docs/CODE_OF_CONDUCT.md ?)

### Roadmap:

* Update the ROADMAP.md file if it's outdated.
* Document how decisions were made to add new features like "AI Inference" support.

### Separation of vendor and community hats:

* Clearly distinguish the WasmEdge CNCF project from the company (Second State) on websites and resources.
* Separate community channels (like Discord) from vendor-specific channels.

### Specific items to complete before reapplying for incubation:

- [ ] Complete the CNCF TAG-Security Security Assessment (TSSA) Process.
- [ ] Complete the CNCF TAG-Contributor-Strategy Governance Review.
- [ ] Work with the CNCF TAG Runtime to get insights and recommendations for the project in the context of the landscape.

By addressing these points, the WasmEdge project can improve its governance, security practices, code of conduct, and overall transparency, fostering a strong and inclusive community/

When you resubmit in say 4-6 months, the TOC can give your project high priority given it is a resubmit for the project. Thanks a ton for your work in the community!

**Comment by dims** [comment]
Marked this as `not-ready` for now. I'll leave this open for a few days for any follow up questions and close it end of the week. thanks!

**Comment by dims** [comment]
Going to close - please reopen/reapply when the project meets the requirements outlined [earlier in this issue.](https://github.com/cncf/toc/issues/1316#issuecomment-2147922883) Do reach out if you have any questions!

**Comment by alabulei1** [comment]
Hi @dims 

Thanks for your valuable feedback. We will work hard to add the missing documentation and the self-assessments for security and governance.

**Comment by alabulei1** [comment]
Hi @dims ,

Thanks for your valuable feedback, which makes WasmEdge a stronger community.
Just want to update the progress we have made some progress in the past two months. Let me know if there is any improvements we can make.

### Governance:

 * Consider adding a section for sub-projects if there are any
 > WasmEdge doesn't have a sub-project. WasmEdge is the main repo, including the plugins.

 * Add information about emeritus maintainers if applicable.
 > WasmEdge doesn't have any emeritus maintainers.

 * Document the Developer Certificate of Origin (DCO) process somewhere.
 > We have added the DCO process in the contributor guide documentation. See [here](https://wasmedge.org/docs/contribute/#sign-your-commits).

 * If it's a single vendor project, consider having a "Council" for roadmap decisions, similar to the CNCF template here - https://contribute.cncf.io/maintainers/templates/
 > WasmEdge follows [the CNCF governance mainater](https://github.com/WasmEdge/WasmEdge/blob/master/docs/GOVERNANCE.md), ie council. For the roadmap discussion, the maintainers will have a public discussion via GitHub issues before it's implemented. See an example [here](https://github.com/WasmEdge/WasmEdge/issues/3473).

 * Document how technical decisions are made, including whether the design process is public, whether non-maintainers can participate, and provide examples of decisions made in a neutral/community-based fashion.
 > For each quarter's technical roadmap decision, there will be a public discussion via GitHub issue. Everyone is welcome to join the conversation. 
 > * See an example [here](https://github.com/WasmEdge/WasmEdge/issues/3473).
 > * See the process [here](https://github.com/WasmEdge/WasmEdge/blob/master/docs/ROADMAP.md#planning-for-roadmap)

 ### Security:
 * The security process should be owned and run by community participants, not just a vendor (see email in SECURITY.md)
 > We have changed the email to an email group created by CNCF. See the documents [here](https://github.com/WasmEdge/WasmEdge/blob/master/SECURITY.md#reporting-a-vulnerability).

 * Adopt suggestions from the CNCF security guidelines, especially regarding embargoes and notifications - https://contribute.cncf.io/maintainers/security/security-guidelines/
 > Yes, the current WasmEdge security policies follow CNCF security guidelines. We added a [disclosure policy documentation](https://github.com/WasmEdge/WasmEdge/blob/master/SECURITY.md#disclosure-policy) and [embargo policy documentation](https://github.com/WasmEdge/WasmEdge/blob/master/docs/embargo-policy.md).

 * Consider using the CNCF tag-security templates for security-related files - https://github.com/cncf/tag-security/tree/main/project-resources
 > Yes. The WasmEdge's `security.md`, `SECURITY_CONTACTS.md`, and `embargo-policy.md` were created by using the CNCF tag-security templates.

 ### Code of Conduct:
 * Separate the dependency/license/copyright information from the CODE_OF_CONDUCT.md file.
 > Yes, the WasmEdge license is a single file from day 1. See [here](https://github.com/WasmEdge/WasmEdge/blob/master/LICENSE.spdx).

 * Have a dedicated email address or contact point for reporting conduct issues, separate from the general mailing list ( [WasmEdge@googlegroups.com](mailto:WasmEdge@googlegroups.com) )
> Besides the general mailing list, community members also can report conduct issues by sending an email to a private email list cncf-wasmedge-runtime-maintainers@lists.cncf.io.

 * Ensure that the CODE_OF_CONDUCT.md files in different repositories are consistent and point to the correct location. ( https://github.com/WasmEdge/docs/blob/main/CODE_OF_CONDUCT.md should point to https://github.com/WasmEdge/WasmEdge/blob/master/docs/CODE_OF_CONDUCT.md ?)

> Updated. See [here](https://github.com/WasmEdge/docs?tab=coc-ov-file).
 
 ### Roadmap:
 
 * Update the ROADMAP.md file if it's outdated.
 > See the ongoing Q3 Roadmap file [here](https://github.com/WasmEdge/WasmEdge/blob/master/docs/ROADMAP.md#current-roadmap).

 * Document how decisions were made to add new features like "AI Inference" support.
 > As mentioned before, for each quater's technical roadmap decision, there will be a public disscusion via GitHub issue. Everyone is welcome to join the coversation. See the policy [here](https://github.com/WasmEdge/WasmEdge/blob/master/docs/ROADMAP.md#planning-for-roadmap).
 
 ### Separation of vendor and community hats:
 * Clearly distinguish the WasmEdge CNCF project from the company (Second State) on websites and resources.
 > Second State and WasmEdge have separate websites and social media accounts. We have been consistently clear in our communications that Second State is one of WasmEdge contributors and it provides commercial services around the WasmEdge open-source software.


 * Separate community channels (like Discord) from vendor-specific channels.
 > WasmEdge now has two community channels, Discord, and Slack, which are designed for community and without vendor branding.
 
 ### Specific items to complete before reapplying for incubation:
 * [ ]  Complete the CNCF TAG-Security Security Assessment (TSSA) Process.
 > It's an ongoing work. We don't have an expected time right now. See the PR [here](https://github.com/cncf/tag-security/pull/1343).

 * [ ]  Complete the CNCF TAG-Contributor-Strategy Governance Review.
 > It's an ongoing work, which is expected to be completed in early September. See the request issue [here](https://github.com/cncf/tag-contributor-strategy/issues/690).

 * [ ]  Work with the CNCF TAG Runtime to get insights and recommendations for the project in the context of the landscape.
 > We demoed WasmEdge in the wg-wasm under the CNCF TAG Runtime when we raised the incubation issue. See the video [here](https://youtu.be/1VsoJ2hBLBk). Should we reach out to the CNCF TAG Runtime again?
