### ISSUE TITLE
Tracking Issue: TAG Documentation Update

### ISSUE THREAD

**Issue by riaankleinhans** [cncf/toc#1366]
### TAG App Delivery

- [ ] TAG App Delivery Repo issue [#712](https://github.com/cncf/tag-app-delivery/issues/712)
  - [ ] PR updating TAG repo README in accordance to the TOC [template](https://github.com/cncf/toc/blob/main/tags/resources/tag-formation-templates/template-tag-readme.md)
  - [ ] PR updating TAG charter in the TOC repo [charter folder](https://github.com/cncf/toc/tree/main/tags/tag-charters) according to the TOC [template](https://github.com/cncf/toc/blob/main/tags/resources/tag-formation-templates/template-tag-charter.md)
  - [ ] Move all TAG related shared documents ( Like meeting notes and slides ) to the [projects@cncf.io](mailto:projects@cncf.io) drive for the TAG.
  The aim of this update is to ensure no documents get lost in private or company accounts. Reach out to @riaankleinhans for assistance on that.

### TAG Contributor Strategy
- [ ]  TAG Contributor Strategy Repo issue [#671](https://github.com/cncf/tag-contributor-strategy/issues/671)
  - [x]  PR updating TAG repo README in accordance to the [template](https://github.com/cncf/toc/blob/main/tags/resources/tag-formation-templates/template-tag-readme.md) https://github.com/cncf/tag-contributor-strategy/pull/650
  - [x]  PR removing TAG repo charter https://github.com/cncf/tag-contributor-strategy/pull/650
  - [ ] PR updating TAG charter in the TOC repo [charter folder](https://github.com/cncf/toc/tree/main/tags/tag-charters) according to the [template](https://github.com/cncf/toc/blob/main/tags/resources/tag-formation-templates/template-tag-charter.md)
  The aim of this update is to ensure that no information is lost from the TAG’s repo level charter.
  - [x]  Move all TAG related shared documents ( Like meeting notes and slides ) to the [projects@cncf.io](mailto:projects@cncf.io) drive for the TAG.
  The aim of this update is to ensure no documents get lost in private or company accounts. Reach out to @riaankleinhans for assistance on that.

### TAG Environmental Sustainability
- [ ]  TAG Environmental Sustainability Repo issue [#457](https://github.com/cncf/tag-env-sustainability/issues/457)
  - [ ]  PR updating TAG repo README in accordance to the [template](https://github.com/cncf/toc/blob/main/tags/resources/tag-formation-templates/template-tag-readme.md)
  - [ ] PR updating TAG charter in the TOC repo [charter folder](https://github.com/cncf/toc/tree/main/tags/tag-charters) according to the [template](https://github.com/cncf/toc/blob/main/tags/resources/tag-formation-templates/template-tag-charter.md)
  - [ ] Move all TAG related shared documents ( Like meeting notes and slides ) to the [projects@cncf.io](mailto:projects@cncf.io) drive for the TAG.
  The aim of this update is to ensure no documents get lost in private or company accounts. Reach out to @riaankleinhans for assistance on that.

### TAG Network
- [ ] TAG Network Repo issue [#42](https://github.com/cncf/tag-network/issues/42)
  - [x] PR updating TAG repo README in accordance to the [template](https://github.com/cncf/toc/blob/main/tags/resources/tag-formation-templates/template-tag-readme.md) and removing TAG repo charter information from the README https://github.com/cncf/tag-network/pull/45
  - [x]  PR updating TAG charter in the TOC repo [charter folder](https://github.com/cncf/toc/tree/main/tags/tag-charters) according to the [template](https://github.com/cncf/toc/blob/main/tags/resources/tag-formation-templates/template-tag-charter.md) https://github.com/cncf/toc/pull/1395
  The aim of this update is to ensure that no information is lost from the TAG’s repo level charter.
  - [ ]  Move all TAG related shared documents ( Like meeting notes and slides ) to the [projects@cncf.io](mailto:projects@cncf.io) drive for the TAG.
  The aim of this update is to ensure no documents get lost in private or company accounts. Reach out to @riaankleinhans for assistance on that.

### TAG Observability

- [ ]  TAG Observability Repo issue [#182](https://github.com/cncf/tag-observability/issues/182)
  - [ ]  PR updating TAG repo README in accordance to the [template](https://github.com/cncf/toc/blob/main/tags/resources/tag-formation-templates/template-tag-readme.md)
  - [ ] PR removing TAG repo charter
  - [ ] PR updating TAG charter in the TOC repo [charter folder](https://github.com/cncf/toc/tree/main/tags/tag-charters) according to the [template](https://github.com/cncf/toc/blob/main/tags/resources/tag-formation-templates/template-tag-charter.md)
  The aim of this update is to ensure that no information is lost from the TAG’s repo level charter.
  - [ ] Move all TAG related shared documents ( Like meeting notes and slides ) to the [projects@cncf.io](mailto:projects@cncf.io) drive for the TAG.
  The aim of this update is to ensure no documents get lost in private or company accounts. Reach out to @riaankleinhans for assistance on that.

### TAG Runtime
- [ ]  TAG Runtime Repo issue [#166](https://github.com/cncf/tag-runtime/issues/166)
  - [ ]  PR updating TAG repo README in accordance to the [template](https://github.com/cncf/toc/blob/main/tags/resources/tag-formation-templates/template-tag-readme.md)
  - [ ] PR removing TAG repo charter
  - [ ] PR updating TAG charter in the TOC repo [charter folder](https://github.com/cncf/toc/tree/main/tags/tag-charters) according to the [template](https://github.com/cncf/toc/blob/main/tags/resources/tag-formation-templates/template-tag-charter.md)
  The aim of this update is to ensure that no information is lost from the TAG’s repo level charter.
  - [ ] Move all TAG related shared documents ( Like meeting notes and slides ) to the [projects@cncf.io](mailto:projects@cncf.io) drive for the TAG.
  The aim of this update is to ensure no documents get lost in private or company accounts. Reach out to @riaankleinhans for assistance on that.

### TAG  Security
- [x] TAG Security Repo issue [#1312](https://github.com/cncf/tag-security/issues/1312)
  - [x]  PR updating TAG repo README in accordance to the [template](https://github.com/cncf/toc/blob/main/tags/resources/tag-formation-templates/template-tag-readme.md) https://github.com/cncf/tag-security/pull/1316
  - [x] PR removing TAG repo charter https://github.com/cncf/tag-security/pull/1316
  - [X] PR updating TAG charter in the TOC repo [charter folder](https://github.com/cncf/toc/tree/main/tags/tag-charters) according to the [template](https://github.com/cncf/toc/blob/main/tags/resources/tag-formation-templates/template-tag-charter.md) https://github.com/cncf/toc/pull/1376
  The aim of this update is to ensure that no information is lost from the TAG’s repo level charter.
  - [x] Move all TAG related shared documents ( Like meeting notes and slides ) to the [projects@cncf.io](mailto:projects@cncf.io) drive for the TAG.
  The aim of this update is to ensure no documents get lost in private or company accounts. Reach out to @riaankleinhans for assistance on that.

### TAG Storage
- [ ] TAG Storage Repo issue [#88](https://github.com/cncf/tag-storage/issues/88)
  - [ ] PR updating TAG repo README in accordance to the [template](https://github.com/cncf/toc/blob/main/tags/resources/tag-formation-templates/template-tag-readme.md)
  - [ ] PR removing TAG repo charter
  - [ ] PR updating TAG charter in the TOC repo [charter folder](https://github.com/cncf/toc/tree/main/tags/tag-charters) according to the [template](https://github.com/cncf/toc/blob/main/tags/resources/tag-formation-templates/template-tag-charter.md)
  The aim of this update is to ensure that no information is lost from the TAG’s repo level charter.
  - [ ] Move all TAG related shared documents ( Like meeting notes and slides ) to the [projects@cncf.io](mailto:projects@cncf.io) drive for the TAG.
  The aim of this update is to ensure no documents get lost in private or company accounts. Reach out to @riaankleinhans for assistance on that.
