### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] werf

### ISSUE THREAD

**Issue by amye** [cncf/toc#977]
Welcome to CNCF Project Onboarding!
This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project.
We would like to complete onboarding within one month of acceptance.

From the project side, please ensure that you:

- [ ] Understand the project proposal process and reqs: <https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction>
- [ ] Understand the services available for your project at CNCF <https://www.cncf.io/services-for-projects/>
- [ ] Ensure your project meets the CNCF IP Policy: <https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy>
- [ ] Review the online programs guidelines: <https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md>
- [ ] Understand the trademark guidelines: <https://www.linuxfoundation.org/en/trademark-usage/>
- [ ] Understand the license allowlist: <https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist>
- [ ] Is your project working on written, open governance? see <https://contribute.cncf.io/maintainers/governance/>
- [ ] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see <https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another> for more details)
- [ ] Is your project in its own separate neutral github organization?
- [ ] Submitted a Pull request to add your project as a sandbox project to <https://landscape.cncf.io>
- [ ] Create maintainer list + add to aggregated <https://maintainers.cncf.io> list by submitting a PR to it
- [ ] Have added your project to <https://github.com/cncf/contribute>
- [ ] Artwork: Submit a pull request to <https://github.com/cncf/artwork> with your artwork
- [ ] Domain: transfer domain to the CNCF - <https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63>

Things that CNCF will need from the project:

- [ ] Provide emails for the maintainers added to <https://maintainers.cncf.io> in order to get access to the maintainers mailing list and ServiceDesk
- [ ] Trademarks: transfer any trademark and logo mark assets over to the LF - <https://github.com/cncf/foundation/tree/master/agreements> has agreements
- [ ] GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
- [ ] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [ ] GitHub: ensure that hat the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
- [ ] Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).
- [ ] Website: Analytics transferred to projects@cncf.io
- [ ] CII: Start on a CII best practices badge <https://bestpractices.coreinfrastructure.org/en>

Things that the CNCF will do or help the project to do:

- [ ] Devstats: add to devstats <https://devstats.cncf.io/>
- [ ] Marketing: update relevant intro + slide decks
- [ ] Events: update CFP + Registration + CFP Area forms
- [ ] ServiceDesk: confirm maintainers have read <https://www.cncf.io/services-for-projects/>
- [ ] CNCF Welcome Email Sent to confirm maintainer list access, welcome email has monthly project sync details
- [ ] Create space for meetings/events on <https://community.cncf.io>, e.g., <https://community.cncf.io/pravega-community/> - (<https://github.com/cncf/communitygroups/blob/main/README.md#cncf-projects>)
- [ ] Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)

**Comment by lukaszgryglicki** [comment]
DevStats page [added](https://werf.devstats.cncf.io).

**Comment by alexey-igrychev** [comment]
> Welcome to CNCF Project Onboarding!
> This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project.
> We would like to complete onboarding within one month of acceptance.
❤️

From the project side, please ensure that you:

* [x]  Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction
* [x]  Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
* [ ]  Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
* [x]  Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
* [x]  Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/
* [x]  Understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist
* [ ]  Is your project working on written, open governance? see https://contribute.cncf.io/maintainers/governance/
* [x]  Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another for more details)
  - We already have the channel in CNCF Slack.
* [x]  Is your project in its own separate neutral github organization?
* [x]  Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io
  - https://github.com/cncf/landscape/pull/2972
* [x]  Create maintainer list + add to aggregated https://maintainers.cncf.io list by submitting a PR to it
  - https://github.com/cncf/foundation/pull/492
* [x]  ~Have added your project to https://github.com/cncf/contribute~
* [ ] Artwork: Submit a pull request to https://github.com/cncf/artwork with your artwork
  - **WIP**
* [ ] Domain: transfer domain to the CNCF - https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63
  - **WIP**

Things that CNCF will need from the project:
 
* [ ]  Provide emails for the maintainers added to https://maintainers.cncf.io in order to get access to the maintainers mailing list and ServiceDesk
  - **WIP**
* [ ]  Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
  - **WIP**
* [x]  GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
* [x]  GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
   - Added DCO GitHub App 
* [x]  GitHub: ensure that hat the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
  - https://github.com/werf/werf/blob/main/CODE_OF_CONDUCT.md
* [ ]  Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).
  - **WIP**
* [ ]  Website: Analytics transferred to [projects@cncf.io](mailto:projects@cncf.io)
  - **WIP**
* [x]  CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en
  - https://bestpractices.coreinfrastructure.org/en/projects/2503

**Comment by alexey-igrychev** [comment]
- [x] Artwork: Submit a pull request to https://github.com/cncf/artwork with your artwork
  - https://github.com/cncf/artwork/pull/391

**Comment by alexey-igrychev** [comment]
> Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements

@amye Where can we send the agreement?

**Comment by amye** [comment]
> > Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
> 
> @amye Where can we send the agreement?

Sending it to me is fine, amye@linuxfoundation.org

**Comment by alexey-igrychev** [comment]
- [x] Provide emails for the maintainers added to https://maintainers.cncf.io/ in order to get access to the maintainers mailing list and ServiceDesk 
- [x]  Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements

**Comment by shurup** [comment]
> Domain: transfer domain to the CNCF - https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63

[The relevant request](https://jira.linuxfoundation.org/plugins/servlet/desk/portal/2/IT-25081) was created.

> Website: Analytics transferred to [projects@cncf.io](mailto:projects@cncf.io)

I have invited this email as a GA property Administrator yesterday. This invitation doesn't seem to be confirmed yet.

**Comment by alexey-igrychev** [comment]
- [x] Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
- [x] Is your project working on written, open governance? see https://contribute.cncf.io/maintainers/governance/

**Comment by alexey-igrychev** [comment]
@amye Our team has completed all the necessary steps. Please let us know if there is anything else we can assist you with.

**Comment by shurup** [comment]
Hi @Cmierly! 

I was responsible for two of these tasks:

>  Domain: transfer domain to the CNCF

[This issue](https://jira.linuxfoundation.org/plugins/servlet/desk/portal/2/IT-25081) (linked above) states that "werf has been successfully transferred over" on 26/Jan/23.

> Website: Analytics transferred to [projects@cncf.io](mailto:projects@cncf.io)

This should have been completed since I see projects@cncf.io listed as Administrator in the relevant GA Property access management settings. Please let me know if we need to do anything else.

Aleksei will comment on two other items ASAP.

**Comment by alexey-igrychev** [comment]
Hi @Cmierly,

Thank you for reaching out, and welcome to the team! I appreciate your support in onboarding sandbox projects.
Regarding the tasks you mentioned:

> Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).

I can confirm that we have ensured the LF footer is in place, and we have followed the website guidelines. You can verify this on our dedicated website: [werf.io](https://werf.io/).

> Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)

We are currently in the process of adopting a license-scanning tool. I will provide an update on our progress by next week.🙏🏼

**Comment by alexey-igrychev** [comment]
> Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)
Done. Finally, we added Snyk to our processes.

**Comment by krook** [comment]
Hello @alexey-igrychev and @Cmierly the final step is to add the werf org and main repo to LFX Insights. 

This is done by adding a GitHub app to the werf organization (similar to the DCO bot).

Once we add it public, read-only, data will flow into the [LFX Insights v3 dashboard](https://insights.v3.lfx.linuxfoundation.org/foundation/cncf).

I'll let you know when this is done.

**Comment by krook** [comment]
LFX Insights onboarding is complete 🎉 

I believe this was the last tasks @Cmierly
